# NumPy Module

In [3]:
import numpy as np
import time
import sys

In [2]:
np.array([1,2,3])

# its similar to a list - access the elements by index 

#then why numpy ?

array([1, 2, 3])

less memory
fast
convinent


In [10]:
l = range(1000)
print(sys.getsizeof(5)*len(l))
#28000 bytes

array = np.arange(1000)
print(array.size*array.itemsize)
# 8000 bytes

28000
8000


In [13]:
SIZE =100000
# create a list
l1 = range(SIZE) 
l2 = range(SIZE)
# create an array
a1 = np.arange(SIZE)
a2 = np.arange(SIZE)

# measure the time between the list and array processing

# python list
start = time.time()
result  = [x+y for x, y in zip(l1,l2)]
print('python list this',(time.time()-start)*1000)

# numpy array
start = time.time()
result = a1 +a2 
print('my numpy took this',(time.time()-start)*1000)

# when processing millions of numbers numpy makes sense as the process tike is faster


python list this 60.91785430908203
my numpy took this 2.8121471405029297


#### Basic Operations 

#### array data types

In [25]:
a = np.array([5,6,9])
print(a.ndim)
print(a[0])

1
5


In [164]:
a= np.array([[1,2],[2,3],[3,4]])
print(a.ndim) # print dimensions of the array

a.itemsize # byte size of each elemets - int elements each size is 4 bytes 

# float size -

2


8

In [29]:
a.dtype # array dta atype

dtype('int64')

In [33]:
a= np.array([[1,2],[2,3],[3,4]],dtype = np.float64)
print(a.dtype)
print(a)

float64
[[1. 2.]
 [2. 3.]
 [3. 4.]]


In [36]:
# size 

print(a.size) # num of elements in the array

print(a.shape) # rows and col

6
(3, 2)


In [38]:
#initialize array with specific data type

a= np.array([[1,2],[2,3],[3,4]],dtype = complex)
print(a)

[[1.+0.j 2.+0.j]
 [2.+0.j 3.+0.j]
 [3.+0.j 4.+0.j]]


# Initializing Different Types of Arrays

In [42]:
# initialize arrat with placeholder number or zeros
print(np.zeros((3, 4)))
print(np.ones((3,4)))
print(np.zeros((2, 2)))


[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]
[[1. 1. 1. 1.]
 [1. 1. 1. 1.]
 [1. 1. 1. 1.]]
[[0. 0.]
 [0. 0.]]


In [167]:
# All 1s matrix
np.ones((4,2,3), dtype='int32') # 4 arrays fo 2X3 size

array([[[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]],

       [[1, 1, 1],
        [1, 1, 1]]], dtype=int32)

In [168]:
# Any other number
np.full((2,2), 99)

array([[99, 99],
       [99, 99]])

In [169]:
# Any other number (full_like)
np.full_like(a, 4) # takes size of a and creates an array of the same size with specified number

array([[4, 4],
       [4, 4],
       [4, 4]])

In [170]:
# Random decimal numbers
np.random.rand(4,2) # creates a random decimal bwtween 0 and 1 in the size 4X2

array([[0.50313671, 0.42335728],
       [0.42319215, 0.56640316],
       [0.69914178, 0.0391944 ],
       [0.11532133, 0.84950968]])

In [171]:
# Random Integer values
np.random.randint(-4,8, size=(3,3)) # creates an array with random integers vetween -4 and 8 in th size 3X3

array([[ 5, -2, -2],
       [-3,  3,  4],
       [ 3,  1, -3]])

In [172]:
# The identity matrix
np.identity(5)


array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

In [174]:
# Repeat an array
arr = np.array([[1,2,3]])
r1 = np.repeat(arr,3, axis=0) # if there is an array with one row and you wnat the same elements in next 3 rows
print(r1)

[[1 2 3]
 [1 2 3]
 [1 2 3]]


In [176]:
output = np.ones((5,5))
print(output)

z = np.zeros((3,3))
z[1,1] = 9 # create a zero array and assign the 1st roe 1st colum elemet to 9
print(z)

output[1:-1,1:-1] = z # expand the z matrix 
print(output)


[[1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1.]]
[[0. 0. 0.]
 [0. 9. 0.]
 [0. 0. 0.]]
[[1. 1. 1. 1. 1.]
 [1. 0. 0. 0. 1.]
 [1. 0. 9. 0. 1.]
 [1. 0. 0. 0. 1.]
 [1. 1. 1. 1. 1.]]


In [178]:
# Be careful when copying arrays!!! 
a = np.array([1,2,3])
b = a.copy()
b[0] = 100

print(a)
b


[1 2 3]


array([100,   2,   3])

#### range

In [60]:
l = range(5)
print(l) # in python , to create a list of number 0 to 5
print(l[4])

# can be done in numpy as well 
print(np.arange(1,5)) # creates an array from 1 to 4 
print(np.arange(1,10,2)) # 1-10 number with a step of 2
print(np.linspace(1,5,10)) # generate 10 numbers between 1 and 5 which are linearly spaced
print(np.linspace(1,5,5))

# reshape
a= np.array([[1,2],[2,3],[3,4]])
print(a)
print(a.shape)
print(a.reshape(2,3))
print(a.reshape(6,1)) # 
print(a.ravel()) # can also be used to flatten the data like one row

print(a) # all these methods will not alter the original array , so assign a variable if you like to use them later


range(0, 5)
4
[1 2 3 4]
[1 3 5 7 9]
[1.         1.44444444 1.88888889 2.33333333 2.77777778 3.22222222
 3.66666667 4.11111111 4.55555556 5.        ]
[1. 2. 3. 4. 5.]
[[1 2]
 [2 3]
 [3 4]]
(3, 2)
[[1 2 2]
 [3 3 4]]
[[1]
 [2]
 [2]
 [3]
 [3]
 [4]]
[1 2 2 3 3 4]
[[1 2]
 [2 3]
 [3 4]]


#### mathematical elements

#### statistics

In [68]:
a= np.array([[1,2],[2,3],[3,4]])

print('min',a.min())
print('max',a.max())
print('sum',a.sum())

# axis 0 - col , axis 1 - row

print('array',a)
print('col sum',a.sum(axis=0))
print('row sum',a.sum(axis=1))

print('square root',np.sqrt(a))
print('standard deviation',np.std(a)) # std deviation of all the numbers

min 1
max 4
sum 15
array [[1 2]
 [2 3]
 [3 4]]
col sum [6 9]
row sum [3 5 7]
square root [[1.         1.41421356]
 [1.41421356 1.73205081]
 [1.73205081 2.        ]]
standard deviation 0.9574271077563381


In [70]:
# numpy arrays

a1 = np.array([1,2,3])
a2 =np.array([4,5,6])

print('sum',a1+a2)
print('diff',a2-a1)
print('multi',a1*a2)
print('division',a1/a2)
print('matrix prduct',a1.dot(a2))

sum [5 7 9]
diff [3 3 3]
multi [ 4 10 18]
division [0.25 0.4  0.5 ]
matrix prduct 32


#### Indexing slicing 

In [76]:
# regular array
n =[6,7,8]
n[0:2] # prints 0, 1 elements
print(n[-1])

8


In [84]:
# numpy array
a = np.array([6,7,8])
print(a[0:2])
print(a[-1]) # last num print in reverse
print(a[::-1])

[6 7]
8
[8 7 6]


In [100]:
# multidimensional array
a = np.array([[1,2,3],[4,5,6],[6,7,8]])
print(a)
print(a[1,2]) # 1st row , 2nd column element - 0,1,2  0,1,2 

print(a[0:2,2]) # goes 0 to 1st row - then prints 2nd element in these 2 rows
# print(a[:2,2]) - same as above
print(a[0:3,0:2])# goes 0 to 2nd row - then prints 1st and 2nd element in these 2 rows

print(a[-1]) # last row 

print(a[-1,0:2]) # last row 1st and 2nd elements 

print(a[:,1:3]) # : - indicates all rows , 1 to 2 indiates 0, 1 , 2 columns 



[[1 2 3]
 [4 5 6]
 [6 7 8]]
6
[3 6]
[[1 2]
 [4 5]
 [6 7]]
[6 7 8]
[6 7]
[[2 3]
 [5 6]
 [7 8]]


#### Iterating through arrays

In [103]:
a = np.array([[1,2,3],[4,5,6],[6,7,8]])

# iterates through every element in the array
for row in a:
    print(row)

[1 2 3]
[4 5 6]
[6 7 8]


In [106]:
# flatten the list and print every number
for cell in a.flat:
        print(cell)
        
#a.flat  this just flattens but does not print hence use for 
#loop to print ot access elements one by one from the flattened array


1
2
3
4
5
6
6
7
8


In [119]:
# reshape into any shape 
a= np.arange(6).reshape(1,6)
print(a)
a= np.arange(6).reshape(2,3)
print(a)

[[0 1 2 3 4 5]]
[[0 1 2]
 [3 4 5]]


#### stacking together  tow arrays

In [122]:
a= np.arange(6).reshape(2,3) # numbers 0 -6 
print(a)
b= np.arange(6,12).reshape(2,3) # numbers 6 -12 
print(b)

[[0 1 2]
 [3 4 5]]
[[ 6  7  8]
 [ 9 10 11]]


In [125]:
print(np.vstack((a,b)))# stacks one array onto the next array specified in the order 

[[ 0  1  2]
 [ 3  4  5]
 [ 6  7  8]
 [ 9 10 11]]


In [126]:
print(np.hstack((a,b)))

[[ 0  1  2  6  7  8]
 [ 3  4  5  9 10 11]]


In [128]:
a= np.arange(30).reshape(2,15)  
print(a)

[[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14]
 [15 16 17 18 19 20 21 22 23 24 25 26 27 28 29]]


In [129]:
np.hsplit(a,3) - split into 3 blocks of 3 arrays 

[array([[ 0,  1,  2,  3,  4],
        [15, 16, 17, 18, 19]]),
 array([[ 5,  6,  7,  8,  9],
        [20, 21, 22, 23, 24]]),
 array([[10, 11, 12, 13, 14],
        [25, 26, 27, 28, 29]])]

In [130]:
result =np.hsplit(a,3) # divide into 3 equal sized arrays
result[0]

array([[ 0,  1,  2,  3,  4],
       [15, 16, 17, 18, 19]])

In [132]:
result =np.vsplit(a,2) # split into 2 arrays 
result[0]

array([[ 0,  1,  2,  3,  4,  5,  6,  7,  8,  9, 10, 11, 12, 13, 14]])

#### Indexing with boolean arrays  Boolean Masking

In [134]:
a= np.arange(12).reshape(3,4)
print(a)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]


In [136]:
b = a>4 # creates a boolean array with true false
print(b) 

[[False False False False]
 [False  True  True  True]
 [ True  True  True  True]]


In [137]:
a[b] - returns all the elemets in a >4

array([ 5,  6,  7,  8,  9, 10, 11])

In [139]:
a[b]=-1 # sets all the values where b = true to -1 
# b can be generated using any condition
a

array([[ 0,  1,  2,  3],
       [ 4, -1, -1, -1],
       [-1, -1, -1, -1]])

# iterate numpy arrays

In [141]:
a =np.arange(12).reshape(3,4)
a

array([[ 0,  1,  2,  3],
       [ 4,  5,  6,  7],
       [ 8,  9, 10, 11]])

In [145]:
for row in a:
    for cell in row:
        print(cell)
    #print(row)

0
1
2
3
4
5
6
7
8
9
10
11


In [144]:
# faltten this array into list
for cell in a.flatten():
    print(cell)


0
1
2
3
4
5
6
7
8
9
10
11


In [ ]:
# nd iter

In [149]:
for x in np.nditer(a,order='C'): # prints elements row by row
    print(x)

0
1
2
3
4
5
6
7
8
9
10
11


In [150]:
for x in np.nditer(a,order='F'): # prints elements column by column 
    print(x)

0
4
8
1
5
9
2
6
10
3
7
11


In [153]:
for x in np.nditer(a,order='F',flags=['external_loop']): # prints entire column on each iteration
    print(x)

[0 4 8]
[1 5 9]
[ 2  6 10]
[ 3  7 11]


In [159]:
a =np.arange(12).reshape(3,4)

# iterate through the elements and modify along
for x in np.nditer(a,op_flags=['readwrite']): # prints entire column on each iteration
   x[...]= x*x

print(a)


[[  0   1   4   9]
 [ 16  25  36  49]
 [ 64  81 100 121]]


In [163]:
#iterate through 2 arrays same time
# shape of the arrays should be same or the shape of one of the arrays be same 
a =np.arange(12).reshape(3,4)
b =np.arange(3,15,4).reshape(3,1)

print(a)
print(b)

for x, y in np.nditer([a,b]):
    print(x,y)

[[ 0  1  2  3]
 [ 4  5  6  7]
 [ 8  9 10 11]]
[[ 3]
 [ 7]
 [11]]
0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11


0 3
1 3
2 3
3 3
4 7
5 7
6 7
7 7
8 11
9 11
10 11
11 11
